linters:
  enable-all: true
  disable:
    - exhaustruct # Disallows to left unused fields in structs
    - exhaustivestruct # Disallows to left unused fields in structs
    - wrapcheck # Disallows to use non-wrapped errors
    - gochecknoinits # Disallows to use init functions
    - ireturn # Disallows to return Interfaces
    - gci # Disable gci import ordering checker since its buggy
    - nilnil # Disallows to use multiple nil return values
    - funlen # Disallows to use long functions
linters-settings:
  cyclop:
    max-complexity: 25
  nestif:
    min-complexity: 6
  gocognit:
    min-complexity: 40

issues:
  exclude:
    - "Function 'Reconcile' has too many statements.*"
    - "Function 'Reconcile' is too long.*"
    - "Function 'Create' is too long.*"
    - "Function 'Mutate' is too long.*"
  exclude-rules:
    - path: .*_webhook.go
      linters:
        - lll
    - path: .*/metrics.go
      linters:
        - gochecknoglobals
    - path: pkg/common/config.go
      linters:
        - lll
run:
  go: '1.19'
  tests: false
  skip-files:
    - cmd/.*.go
    - .*/groupversion_info.go
    - .*/zz_generated.deepcopy.go
