linters:
  enable-all: true
  disable:
    - exhaustruct # Disallows to left unused fields in structs
    - exhaustivestruct # Disallows to left unused fields in structs
    - wrapcheck # Disallows to use non-wrapped errors
    - gochecknoinits # Disallows to use init functions
    - ireturn # Disallows to return Interfaces
    - gci # Disable gci import ordering checker since its buggy
    - forcetypeassert # Disallows to use type assertions without checking
    - depguard # Disallows to use non-listed packages
    - gochecknoglobals # We like global variables
    - tagalign # Buggy
    - lll
    - funlen
linters-settings:
  cyclop:
    max-complexity: 12
run:
  go: '1.22'
  tests: false
  skip-dirs:
    - cmd/benchmark
