linters:
  enable-all: true
  disable:
    - exhaustruct # Disallows to left unused fields in structs
    - exhaustivestruct # Disallows to left unused fields in structs
    - wrapcheck # Disallows to use non-wrapped errors
    - gochecknoinits # Disallows to use init functions
    - ireturn # Disallows to return Interfaces
    - gci # Disable gci import ordering checker since its buggy
issues:
  exclude-rules:
    - path: .*/metrics.go
      linters:
        - gochecknoglobals
    - path: pkg/config.go
      linters:
        - lll
run:
  go: '1.19'
  tests: false
  skip-dirs:
    - cmd/benchmark
