linters:
  enable-all: true
  disable:
    - exhaustruct # Disallows to left unused fields in structs
    - exhaustivestruct # Disallows to left unused fields in structs
    - wrapcheck # Disallows to use non-wrapped errors
    - gochecknoinits # Disallows to use init functions
    - ireturn # Disallows to return Interfaces
    - gci # Disable gci import ordering checker since its buggy
    - depguard # Disallows to use non-listed packages
    - tagalign # Disallows to use non-aligned tags
linters-settings:
  funlen:
    lines: 90
issues:
  exclude-rules:
    - path: .*/metrics.go
      linters:
        - gochecknoglobals
run:
  go: '1.21'
  tests: false
  skip-dirs:
    - cmd/benchmark
  skip-files:
    - cmd/.*.go
    - mocks/.*.go
    - common/config.go
    - .*/groupversion_info.go
    - .*/zz_generated.deepcopy.go