template: testify
dir: "mocks"
filename: "{{.SrcPackagePath}}/mock_{{.InterfaceName}}.go"
packages:
  github.com/NCCloud/mayfly/pkg/common:
    interfaces:
      Scheduler: {}
  sigs.k8s.io/controller-runtime/pkg/cache:
    interfaces:
      Cache: {}
  sigs.k8s.io/controller-runtime/pkg/client:
    interfaces:
      Client: {}
      SubResourceClient: {}
  sigs.k8s.io/controller-runtime/pkg/manager:
    interfaces:
      Manager: {}
