apiVersion: cloud.namecheap.com/v1alpha1
kind: ScheduledResource
metadata:
  name: combination-example
  annotations:
    mayfly.cloud.namecheap.com/expire: 10s
spec:
  in: "5s"
  content: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: combination-example
      namespace: default
      annotations:
        mayfly.cloud.namecheap.com/expire: 10s
    data:
      .secret-file: dmFsdWUtMg0KDQo=