apiVersion: cloud.namecheap.com/v1alpha1
kind: ScheduledResource
metadata:
  name: combination-example
  annotations:
    mayfly.cloud.namecheap.com/expire: "2024-12-31T00:00:00Z"
spec:
  in: "10s"
  content: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: combination-example
      namespace: default
      annotations:
        mayfly.cloud.namecheap.com/expire: "2024-12-31 22:05:00"
    data:
      .secret-file: dmFsdWUtMg0KDQo=