apiVersion: cloud.namecheap.com/v1alpha2
kind: ScheduledResource
metadata:
  name: scheduled-resource-with-expiration-combination
spec:
  schedule: "*/20 * * * * *" # Creates every 20 seconds
  content: |
    apiVersion: v1
    kind: Secret
    metadata:
      generateName: scheduled-resource-with-expiration-combination-example-
      namespace: default
      annotations:
        mayfly.cloud.namecheap.com/expire: "10s" # Deletes in 10 seconds after created
    data:
      .secret-file: dmFsdWUtMg0KDQo=