name: Test
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  contents: write

env:
  GO_VERSION: "1.23"
  GOPRIVATE: "github:com/NCCloud/*"

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        run: |
          ./devops.sh generate
          git diff --exit-code
      - name: Test Preparation
        run: |
          ./devops.sh prepare_envtest
      - name: Coverage Report
        uses: gwatts/go-coverage-action@v2
        id: coverage
        with:
          coverage-threshold: 80
          cover-pkg: ./...
          ignore-pattern: |
            .*cmd.*
            .*mocks.*
            .*apis.*
            .*generated.*
